id: 4
title: check if update to latest ubunto makes sense
state: new
type: ''
labels: []
reporter: ''
assignee: ''
priority: P4
due_date: ''
relationships:
  child:
  - 5
created: 2025-12-22T21:37:06Z
updated: 2026-01-05T20:39:39Z
