id: 5
title: show dancing unicorn while application is loading
state: new
type: feature
labels:
- ui
reporter: ''
assignee: r.federer
priority: ''
due_date: 2042-12-31
relationships:
  parent:
  - 4
created: 2025-12-23T21:14:45Z
updated: 2026-01-05T20:39:39Z
