id: 2
title: possibility to show the logo on the screen
state: new
type: feature
labels:
- driver
- gui
assignee: ''
priority: P2
due_date: 2026-01-30
created: 2025-12-22T21:23:41Z
updated: 2025-12-23T20:25:15Z
