id: 2
title: possibility to show the logo on the screen
state: new
type: feature
labels:
- driver
- gui
reporter: ''
assignee: ''
priority: P2
due_date: 2026-01-30
relationships:
  related:
  - 1
created: 2025-12-22T21:23:41Z
updated: 2025-12-26T17:38:29Z
