id: 1
title: bug in lcd driver
state: closed
type: bug
labels:
- driver
- log
assignee: t.burkard
priority: P2
due_date: ''
relationships: {}
created: 2025-12-22T21:11:36Z
updated: 2025-12-22T21:23:05Z
