id: 1
title: bug in lcd driver
state: closed
type: bug
labels:
- driver
- log
reporter: ''
assignee: t.burkard
priority: P2
due_date: ''
relationships:
  related:
  - 2
  - 3
created: 2025-12-22T21:11:36Z
updated: 2025-12-26T17:42:52Z
