id: 3
title: segmentation fault
state: active
type: bug
labels:
- memsafety
reporter: t.burkard
assignee: j.doe
priority: P1
due_date: ''
relationships:
  related:
  - 1
created: 2025-12-22T21:29:33Z
updated: 2025-12-27T14:28:36Z
